# Set logger level  for diagnosing
# Available value: "NOTSET", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
# Can override level in commandline argument
#log-level = "DEBUG"

# The host part of generated url in updates.xml
# generated url format:
# <base>/<prefix>/<extension-id>/<extension-version>.crx
#base = "http://localhost:8888"

# The prefix of crx path, must starts with /, or we will prepend a /
#prefix = "/crx-repo"

# The path of manifest, must starts with /, or we will prepend a /
# <base>/<prefix>/<manifest-path>
#manifest-path = "/updates.xml"

# Use proxy to connect to google web store
# Simply remove this to connect directly
#proxy = ""

# how many seconds to trigger extension checking.
#interval = 10800

# Which directory is used to storage cache
#cache-dir = "cache"

#[custom-args.chrome]
# Which Chrome/Chromium version sent to Google
#version = "128.0"

# Which extensions to track updating
# Write their id here
#[[extensions]]
#extension-id = ""
#extension-provider = "chrome" # Optional, defaults to "chrome".
#proxy = "" # Optional, use proxy above if not set.
#interval = "" # Optional, use interval above if not set.
#custom-args = {} # Optional, override custom-args.<extension-provider> in main part.

[listen.tcp]
# Listen TCP socket and transport http data
address = "127.0.0.1"
port = 8888

#[listen.tcp.tls]
#cert = "crx-repo.crt"
#key = "crx-repo.key" # Or remove this to use private key in cert
#password = "" # Or remove this to use empty password.
# Can be used on unix socket with key listen.unix.tls

#[listen.unix]
# Listen Unix socket and transport http data
#path = "/run/crx-repo/crx-repo.socket"
#permission = 666
